apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: mats
  namespace: mats-dev
spec:
  rules:
    - host: apps-dev.gsd.esrl.noaa.gov
      http:
        paths:
          - path: /mats/scorecard(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: scorecard
                port:
                  name: http
