resources:
  - cb-metar
  - ceil-vis
  - ceil-vis15
  - ensemble
  - home
  - landuse
  - precipAccum
  - precipGauge
  - precipitation1hr
  - ptype
  - radar
  - scorecard
  - surface
  - surfrad
  - upperair
  - mongo
  - ingress-apps.yaml
  - ingress-home.yaml
commonLabels:
  environment: dev
