apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cb-metar
  - cb-metar-capella
  - ceil-vis
  - ceil-vis15
  - ensemble
  - home
  - landuse
  - precipAccum
  - precipGauge
  - precipitation1hr
  - ptype
  - radar
  - scorecard
  - surface
  - surfrad
  - upperair
  - mongo
  - ingress-apps.yaml
  - ingress-home.yaml

labels:
  - includeSelectors: true
    pairs:
      environment: dev
