apiVersion: apps/v1
kind: Deployment
metadata:
  name: cb-ceiling
spec:
  template:
    spec:
      containers:
        - name: cb-ceiling
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "8Gi"
              cpu: "4"
          envFrom:
            - secretRef:
                name: cb-ceiling-secret
          volumeMounts:
            - name: cb-ceiling-settings-file
              mountPath: /usr/app/settings/cb-ceiling/settings.json
              subPath: settings.json
              readOnly: true
          imagePullPolicy: Always  # Since we track a long-lived tag
      imagePullSecrets:
        - name: mats-ghcr
      volumes:
        - name: cb-ceiling-settings-file
          configMap:
            name: cb-ceiling-config
