apiVersion: apps/v1
kind: Deployment
metadata:
  name: surfrad
spec:
  template:
    spec:
      containers:
        - name: surfrad
          # resources:
          #   requests:
          #     memory: "2Gi"
          #     cpu: "1"
          #   limits:
          #     memory: "4Gi"
          #     cpu: "2"
          envFrom:
            - secretRef:
                name: surfrad-secret
          volumeMounts:
            - name: surfrad-settings-file
              mountPath: /usr/app/settings/surfrad/settings.json
              subPath: settings.json
              readOnly: true
      volumes:
        - name: surfrad-settings-file
          configMap:
            name: surfrad-config
