apiVersion: apps/v1
kind: Deployment
metadata:
  name: landuse
spec:
  template:
    spec:
      containers:
        - name: landuse
          # resources:
          #   requests:
          #     memory: "2Gi"
          #     cpu: "1"
          #   limits:
          #     memory: "4Gi"
          #     cpu: "2"
          envFrom:
            - secretRef:
                name: landuse-secret
          volumeMounts:
            - name: landuse-settings-file
              mountPath: /usr/app/settings/landuse/settings.json
              subPath: settings.json
              readOnly: true
      volumes:
        - name: landuse-settings-file
          configMap:
            name: landuse-config
