version: "2"
run:
  tests: true
linters:
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - durationcheck
    - errname
    - errorlint
    - gomoddirectives
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - nolintlint
    - predeclared
    - promlinter
    - reassign
    - sqlclosecheck
    - tagliatelle
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - usestdlibvars
    - usetesting
    - wastedassign
  settings:
    errcheck:
      exclude-functions:
        - io/ioutil.ReadFile
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)
    gocritic:
      disabled-checks:
        - hugeParam
        - rangeExprCopy
        - rangeValCopy
      enabled-tags:
        - diagnostic
        - opinionated
        - performance
        - style
    nakedret:
      max-func-lines: 1
    tagliatelle:
      case:
        rules:
          avro: snake
          bson: camel
          json: snake
          mapstructure: kebab
          xml: camel
          yaml: snake
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
  new: false
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
