apiVersion: v1
kind: Service
metadata:
  name: precipaccum
  labels:
    app: precipaccum
spec:
  selector:
    app: precipaccum
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http
  type: ClusterIP
