apiVersion: apps/v1
kind: Deployment
metadata:
  name: precipgauge
spec:
  template:
    spec:
      containers:
        - name: precipgauge
          # resources:
          #   requests:
          #     memory: "2Gi"
          #     cpu: "1"
          #   limits:
          #     memory: "4Gi"
          #     cpu: "2"
          envFrom:
            - secretRef:
                name: precipgauge-secret
          volumeMounts:
            - name: precipgauge-settings-file
              mountPath: /usr/app/settings/precipgauge/settings.json
              subPath: settings.json
              readOnly: true
      volumes:
        - name: precipgauge-settings-file
          configMap:
            name: precipgauge-config
