apiVersion: v1
kind: Service
metadata:
  name: landuse
  labels:
    app: landuse
spec:
  selector:
    app: landuse
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http
  type: ClusterIP
