apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cb-metar
  - home
  - mongo
  - ingress-apps.yaml
  - ingress-home.yaml
labels:
  - includeSelectors: true
    pairs:
      environment: dev
