apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceil-vis15
spec:
  template:
    spec:
      containers:
        - name: ceil-vis15
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "8Gi"
              cpu: "4"
          envFrom:
            - secretRef:
                name: ceil-vis15-secret
          volumeMounts:
            - name: ceil-vis15-settings-file
              mountPath: /usr/app/settings/ceil-vis15/settings.json
              subPath: settings.json
              readOnly: true
          imagePullPolicy: Always  # Since we track a long-lived tag
      imagePullSecrets:
        - name: mats-ghcr
      volumes:
        - name: ceil-vis15-settings-file
          configMap:
            name: ceil-vis15-config
