apiVersion: apps/v1
kind: Deployment
metadata:
  name: radar
spec:
  template:
    spec:
      containers:
        - name: radar
          # resources:
          #   requests:
          #     memory: "2Gi"
          #     cpu: "1"
          #   limits:
          #     memory: "4Gi"
          #     cpu: "2"
          envFrom:
            - secretRef:
                name: radar-secret
          volumeMounts:
            - name: radar-settings-file
              mountPath: /usr/app/settings/radar/settings.json
              subPath: settings.json
              readOnly: true
      volumes:
        - name: radar-settings-file
          configMap:
            name: radar-config
