resources:
  - ../../../base/home

patchesStrategicMerge:
  - deployment.yaml

images:
  - name: ghcr.io/noaa-gsl/mats/development/home
    newTag: development

configMapGenerator:
  - name: home-config
    files:
      - settings.json # Should mirror the appropriate settings.json file in mats-settings
