apiVersion: apps/v1
kind: Deployment
metadata:
  name: surface
spec:
  template:
    spec:
      containers:
        - name: surface
          # resources:
          #   requests:
          #     memory: "2Gi"
          #     cpu: "1"
          #   limits:
          #     memory: "4Gi"
          #     cpu: "2"
          envFrom:
            - secretRef:
                name: surface-secret
          volumeMounts:
            - name: surface-settings-file
              mountPath: /usr/app/settings/surface/settings.json
              subPath: settings.json
              readOnly: true
      volumes:
        - name: surface-settings-file
          configMap:
            name: surface-config
