apiVersion: apps/v1
kind: Deployment
metadata:
  name: cb-metar
spec:
  template:
    spec:
      containers:
        - name: cb-metar
          # resources:
          #   requests:
          #     memory: "2Gi"
          #     cpu: "1"
          #   limits:
          #     memory: "4Gi"
          #     cpu: "2"
          envFrom:
            - secretRef:
                name: cb-metar-secret
          volumeMounts:
            - name: cb-metar-settings-file
              mountPath: /usr/app/settings/cb-metar/settings.json
              subPath: settings.json
              readOnly: true
      volumes:
        - name: cb-metar-settings-file
          configMap:
            name: cb-metar-config
