apiVersion: v1
kind: Service
metadata:
  name: home
  labels:
    app: home
spec:
  selector:
    app: home
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP
