apiVersion: v1
kind: Service
metadata:
  name: radar
  labels:
    app: radar
spec:
  selector:
    app: radar
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http
  type: ClusterIP
