apiVersion: v1
kind: Service
metadata:
  name: ceil-vis
  labels:
    app: ceil-vis
spec:
  selector:
    app: ceil-vis
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http
  type: ClusterIP
