apiVersion: v1
kind: Service
metadata:
  name: surfrad
  labels:
    app: surfrad
spec:
  selector:
    app: surfrad
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http
  type: ClusterIP
