apiVersion: v1
kind: Service
metadata:
  name: ensemble
  labels:
    app: ensemble
spec:
  selector:
    app: ensemble
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http
  type: ClusterIP
