apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/description: mongo database
  creationTimestamp: "2022-09-07T23:06:28Z"
  generation: 1
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-scorecard-mongo
    manager: k3s
    operation: Update
  name: mongo
  namespace: scorecard
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-scorecard-mongo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-scorecard-mongo
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: Adm1n0
        - name: MONGO_INITDB_DATABASE
          value: admin
        image: mongo:5.0
        imagePullPolicy: IfNotPresent
        name: container-0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/db
          name: matsdata
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: matsdata
        persistentVolumeClaim:
          claimName: matsdata
