resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
- name: scorecard-config
  files:
    - settings.json # Should mirror the appropriate settings.json file in mats-settings

secretGenerator:
  - name: scorecard-secret
    envs:
    - .env # Should contain mongo_url, root_url, and delay