apiVersion: v1
kind: Service
metadata:
  name: scorecard
  labels:
    app: scorecard
spec:
  selector:
    app: scorecard
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http
  type: ClusterIP
