apiVersion: apps/v1
kind: Deployment
metadata:
  name: scorecard
spec:
  template:
    spec:
      containers:
        - name: scorecard
          envFrom:
            - secretRef:
                name: scorecard-secret
          volumeMounts:
            - name: scorecard-settings-file
              mountPath: /usr/app/settings/scorecard/settings.json
              subPath: settings.json
              readOnly: true
      volumes:
        - name: scorecard-settings-file
          configMap:
            name: scorecard-config
