apiVersion: v1
kind: Service
metadata:
  name: cb-metar
  labels:
    app: cb-metar
spec:
  selector:
    app: cb-metar
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http
  type: ClusterIP
