apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  template:
    spec:
      containers:
        - name: mongodb
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "1"
          envFrom:
            - secretRef:
                name: mongo-secret
          volumeMounts:
            - name: mongo-config-file
              mountPath: /etc/mongod.conf
              readOnly: true
      volumes:
        - name: mongo-config-file
          configMap:
            name: mongo-config
