version: "3"

networks:
 web:
   external: true
 backend:
   external: false

services:

 traefik:
   container_name: traefik
   image: traefik:1.7.2-alpine
   restart: always
   networks:
     - web
   ports:
     - "80:80"
     - "443:443"
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - $HOME/metexpress_app_configuration/traefik.toml:/traefik.toml
     - $HOME/metexpress_app_configuration/acme.json:/acme.json
   labels:
    - traefik.frontend.rule=Host:proxy.pierce-lt.fsl.noaa.gov
    - traefik.port=8090

 met-http:
  container_name: "met-http"
  image: randytpierce/mats1:met-http
  volumes:
   - $HOME/metexpress_app_configuration/web:/web
  restart: always
  labels:
   - traefik.backend=met-http/index.html
   - traefik.frontend.rule=Host:pierce-lt.fsl.noaa.gov
   - traefik.docker.network=web
   - traefik.port=8080
  networks:
   - web

 mongo:
  container_name: "mongo"
  image: randytpierce/mats1:met-mongo
  ports:
   - "27017:27017"
  volumes:
   - $HOME/mongodata:/data/db
  restart: always
  networks:
   - backend

 met-anomalycor:
  container_name: "met-anomalycor"
  image: randytpierce/mats1:met-anomalycor-dev-2.1.5-2019.03.29.06.49
  environment:
   - DELAY=3
  links:
   - mongo
  volumes:
   - $HOME/metexpress_app_configuration/settings:/usr/app/settings
  depends_on:
   - mongo
  restart: always
  labels:
   - traefik.backend=met-anomalycor
   - traefik.frontend.rule=Host:met-anomalycor.pierce-lt.fsl.noaa.gov
   - traefik.docker.network=web
   - traefik.port=80
  networks:
   - web
   - backend
 
 met-surface:
  container_name: "met-surface"
  image: randytpierce/mats1:met-surface-dev-2.1.5-2019.03.29.06.00
  environment:
   - DELAY=3
  links:
   - mongo
  volumes:
   - $HOME/metexpress_app_configuration/settings:/usr/app/settings
  depends_on:
   - mongo
  restart: always
  labels:
   - traefik.backend=met-surface
   - traefik.frontend.rule=Host:met-surface.pierce-lt.fsl.noaa.gov
   - traefik.docker.network=web
   - traefik.port=80
  networks:
   - web
   - backend

 met-upperair:
  container_name: "met-upperair"
  image: randytpierce/mats1:met-upperair-dev-2.1.5-2019.03.29.06.15
  environment:
   - DELAY=3
  links:
   - mongo
  volumes:
   - $HOME/metexpress_app_configuration/settings:/usr/app/settings
  depends_on:
   - mongo
  restart: always
  labels:
   - traefik.backend=met-upperair
   - traefik.frontend.rule=Host:met-upperair.pierce-lt.fsl.noaa.gov
   - traefik.docker.network=web
   - traefik.port=80
  networks:
   - web
   - backend

 mats4met-ensemble:
  container_name: "mats4met-ensemble"
  image: randytpierce/mats1:mats4met-ensemble-dev-2.1.5-2019.03.29.06.22
  environment:
   - DELAY=3
  links:
   - mongo
  volumes:
   - $HOME/metexpress_app_configuration/settings:/usr/app/settings
  depends_on:
   - mongo
  restart: always
  labels:
   - traefik.backend=mats4met-ensemble
   - traefik.frontend.rule=Host:mats4met-ensemble.pierce-lt.fsl.noaa.gov
   - traefik.docker.network=web
   - traefik.port=80
  networks:
   - web
   - backend

