defaultEntryPoints = ["http", "https"]
[web]
address = ":8080"
  [web.auth.basic]
  users = ["admin:$apr1$0Rjq9MRS$6OtgeJsDpZOeF9iPbWits0"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
[acme]
email = "randy.pierce@noaa.gov"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false

