resources:
  - ../../../base/ptype

patchesStrategicMerge:
  - deployment.yaml

images:
  - name: ghcr.io/noaa-gsl/mats/development/ptype
    newTag: development 

configMapGenerator:
  - name: ptype-config
    files:
      - settings.json # Should mirror the appropriate settings.json file in mats-settings

secretGenerator:
  - name: ptype-secret
    envs:
      - .env # Should contain mongo_url, root_url, and delay
