apiVersion: v1
kind: Service
metadata:
  name: upperair
  labels:
    app: upperair
spec:
  selector:
    app: upperair
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http
  type: ClusterIP
