apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mats
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: mats.127.0.0.1.nip.io
      http:
        paths:
          - path: /scorecard
            pathType: Prefix
            backend:
              service:
                name: scorecard
                port:
                  number: 80
          - path: /anomalycor
            pathType: Prefix
            backend:
              service:
                name: anomalycor
                port:
                  number: 80
          - path: /cb-ceiling
            pathType: Prefix
            backend:
              service:
                name: cb-ceiling
                port:
                  number: 80
          - path: /ceil-vis
            pathType: Prefix
            backend:
              service:
                name: ceil-vis
                port:
                  number: 80
          - path: /ceil-vis15
            pathType: Prefix
            backend:
              service:
                name: ceil-vis15
                port:
                  number: 80
          - path: /landuse
            pathType: Prefix
            backend:
              service:
                name: landuse
                port:
                  number: 80