apiVersion: apps/v1
kind: Deployment
metadata:
  name: cb-metar
spec:
  template:
    spec:
      containers:
        - name: cb-metar
          resources:
            requests:
              memory: "500Mi" # based on test suite performance, appears to hover around 1 GB
              cpu: "0.25" # based on test suite performance, appears to hover around 1 CPU
            limits:
              memory: "3Gi"
              cpu: "1.5"
          envFrom:
            - secretRef:
                name: cb-metar-secret
          volumeMounts:
            - name: cb-metar-settings-file
              mountPath: /usr/app/settings/cb-metar/settings.json
              subPath: settings.json
              readOnly: true
          imagePullPolicy: Always  # Since we track a long-lived tag
      imagePullSecrets:
        - name: mats-ghcr
      volumes:
        - name: cb-metar-settings-file
          configMap:
            name: cb-metar-config
