apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: mats
    app.kubernetes.io/component: database
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:5.0
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: mongo-config-file
              mountPath: /etc/mongod.conf
              readOnly: true
      volumes:
        - name: mongo-config-file
          configMap:
            name: mongo-config
