resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml

configMapGenerator:
  - name: mongo-config
    files:
      - mongod.conf

secretGenerator:
  - name: mongo-secret
    envs:
    - .env.mongo.secret # Should contain user and password
