apiVersion: apps/v1
kind: Deployment
metadata:
  name: home
spec:
  template:
    spec:
      containers:
        - name: home
          resources:
            requests:
              memory: "500Mi"
              cpu: "0.25"
            limits:
              memory: "2Gi"
              cpu: "1"
          volumeMounts:
            - name: home-settings-file
              mountPath: /app/settings.json
              subPath: settings.json
              readOnly: true
          imagePullPolicy: Always  # Since we track a long-lived tag
      imagePullSecrets:
        - name: mats-ghcr
      volumes:
        - name: home-settings-file
          configMap:
            name: home-config
