resources:
  - ../../../base/precipAccum

patchesStrategicMerge:
  - deployment.yaml

images:
  - name: ghcr.io/noaa-gsl/mats/development/precipaccum
    newTag: development 

configMapGenerator:
  - name: precipaccum-config
    files:
      - settings.json # Should mirror the appropriate settings.json file in mats-settings

secretGenerator:
  - name: precipaccum-secret
    envs:
      - .env # Should contain mongo_url, root_url, and delay
