resources:
  - anomalycor
  - cb-metar
  - ceil-vis
  - ceil-vis15
  - landuse
  - precipAccum
  - precipGauge
  - precipitation1hr
  - ptype
  - radar
  - scorecard
  - surface
  - surfrad
  - upperair
  - mongo
  - ingress.yaml
commonLabels:
  environment: prod
