@startuml scProcessScorecardData
title scProcessScorecardData
hide footbox
Participant server.processScorecard as processScorecard
Participant Scheduler as scheduler
Participant Schedule as schedule
Participant CalculateService as calcService
Participant CalcDirecdtor as calcDirector
Participant CalcWorker  as calcWorker
Participant Database as dbScorecards
Participant Mongo as mongo
Participant Job as job
Participant ScorecardRestApi as scRestApi
Participant ScorecardApp

processScorecard->processScorecard:creates initial scorecard doc(from params)
processScorecard->:dbScorecards: inserts Scorecard doc into couchbase Scorecard collection
processScorecard->scheduler:schedules job (might be one time immediate or repeating)
job->scheduler:makes blank new scorecard doc (if repeating) inserts Scorecard doc into couchbase
dbScorecards->calcService: event function sends HTTP request to calcService (params scorecard id)
note right: This very much depends \n on the CB event functions knowing \n the difference between an insert \n and an update - inserts go to calcservice \n updates go to scorecard app
calcDirector->calcDirector: gets scoreCard from database
calcDirector->calcDirector: assembles calculations from scorecard doc and supporting CB data
note right: assembling calculations might be a threaded operation
calcDirector->calcQueue **: builds and fills queue with calculations
loop n times
    calcDirector->calcWorker **: creates threads
    loop until queue is empty
    calcWorker<-calcQueue: pulls item from queue
    calcWorker->calcWorker: makes calculation
    calcWorker->calcDirector: gives result to director
    end
    calcWorker->calcWorker !!: worker dies
end
calcDirector->dbScorecards: updates scorecard in database
dbScorecards->scRestApi: sends rest API request to scorecard app to update mongo
scorecardApp->scorecardApp: reads updated scorecard results from couchbase and updates mongo
scorecardApp->scorecardApp: reactive var updates scorecard display dynamically
calcDirector->calcService: Done
caclDirector->calcDirector: !! dies
