apiVersion: v1
kind: Service
metadata:
  name: ptype
  labels:
    app: ptype
spec:
  selector:
    app: ptype
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http
  type: ClusterIP
