apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/mongo

patches:
  - path: deployment.yaml
  # FIXME: We want to use an in-memory store until we have a CSI driver
  - path: delete-pvc.yaml
    target:
      kind: PersistentVolumeClaim
      name: mongo-pv-claim

configMapGenerator:
  - name: mongo-config
    files:
      - mongod.conf

secretGenerator:
  - name: mongo-secret
    envs:
    - .env.mongo.secret # Should contain user and password
