name: "Build"
on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        app: 
          - aircraft
          - anomalycor
          - cb-ceiling
          - ceiling
          - ceiling15
          - compositeReflectivity
          - echotop
          - landuse
          - precipGauge
          - precipitation1hr
          - precipitation24hr
          - precipitationSub24hr
          - ptype
          - raobamdar
          - surface
          - surfrad
          - upperair
          - vil
          - visibility
          - visibility15
    env:
      REGISTRY: ghcr.io/noaa-gsl/mats/development
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Get branch & tag name
        shell: bash
        # Note - this doesn't support branch names with "/" in them
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
            # Handle differences between branches/tags
            if [[ "${GITHUB_REF}" == *"heads"* ]]; then
              echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
            else
              echo "::set-output name=branch::${GITHUB_REF#refs/tags/}"
            fi
          elif [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            echo "::set-output name=branch::${GITHUB_HEAD_REF}"
          else
            echo "::set-output name=branch::UNKNOWN"
          fi
          echo "::set-output name=version::dev"
        id: git-info

      - name: Build container
        run: |
          docker build \
            --build-arg APPNAME=${{ matrix.app }} \
            --build-arg BUILDVER="${{ steps.git-info.outputs.version }}" \
            --build-arg COMMITBRANCH=${{ steps.git-info.outputs.branch }} \
            --build-arg COMMITSHA=${{ github.sha }} \
            -t ${REGISTRY}/${{ matrix.app }}:${{ steps.git-info.outputs.branch }} \
            .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push container
        run: |
          docker push ${REGISTRY}/${{ matrix.app }}:${{ steps.git-info.outputs.branch }}
