name: Cleanup MATS PR images

on: 
  pull_request:
    types: [closed]
    paths-ignore:
      - "home/**"

jobs:
  purge-images:
    name: Cleanup PR images from ghcr.io
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app:
          - cb-metar
          - ceil-vis
          - ceil-vis15
          - ensemble
          - landuse
          - precipAccum
          - precipGauge
          - precipitation1hr
          - ptype
          - radar
          - scorecard
          - surface
          - surfrad
          - upperair
    steps:
      - name: Get tag & appname
        env: 
          APP: '${{ matrix.app }}'
        run: |
          echo "BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
          echo "APP_LOWERCASE=${APP,,}" >> $GITHUB_ENV
      - name: Cleanup images
        if: ${{ (env.BRANCH != 'development') && (env.BRANCH != 'main') }} # don't prune images from the development or main branches
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: noaa-gsl
          name: mats/development/${{ env.APP_LOWERCASE }}
          token: ${{ secrets.GHCR_CLEANUP_PAT }}
          tag: ${{ env.BRANCH }}
