name: Cleanup PR images

on: 
  pull_request:
    types: [closed]

jobs:
  purge-images:
    name: Cleanup PR images from ghcr.io
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app:
          - aircraft
          - anomalycor
          - cb-ceiling
          - ceil-vis
          - ceil-vis15
          - landuse
          - precipAccum
          - precipGauge
          - precipitation1hr
          - ptype
          - radar
          - raobamdar
          - surface
          - surfrad
          - upperair
    steps:
      - name: Get tag & appname
        env: 
          APP: '${{ matrix.app }}'
        run: |
          echo "BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
          echo "APP_LOWERCASE=${APP,,}" >> $GITHUB_ENV
      - name: Cleanup images
        if: env.BRANCH != 'development' # don't prune images from the development branch
        uses: bots-house/ghcr-delete-image-action@v1.0.1
        with:
          owner: noaa-gsl
          name: mats/development/${{ env.APP_LOWERCASE }}
          token: ${{ secrets.GHCR_CLEANUP_PAT }}
          tag: ${{ env.BRANCH }}
