name: Cleanup Untagged GHCR Images

on: 
  workflow_dispatch: # Manually
  schedule:
    - cron: '0 0 * * *' # Every day at midnight

jobs:
  purge-untagged-images:
    name: Delete image from ghcr.io
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app:
          - anomalycor
          - cb-ceiling
          - ceil-vis
          - ceil-vis15
          - landuse
          - precipAccum
          - precipGauge
          - precipitation1hr
          - ptype
          - radar
          - scorecard
          - surface
          - surfrad
          - upperair
    steps:
      - name: Delete image
        uses: snok/container-retention-policy@v1.4.1
        with:
          image-names: mats/development/${{ matrix.app }}
          cut-off: 1 day ago MST
          account-type: org
          org-name: noaa-gsl
          untagged-only: true
          token: ${{ secrets.GHCR_CLEANUP_PAT }}
